# (C) Copyright 2020 ECMWF.
#
# This software is licensed under the terms of the Apache Licence Version 2.0
# which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
# In applying this licence, ECMWF does not waive the privileges and immunities
# granted to it by virtue of its status as an intergovernmental organisation
# nor does it submit to any jurisdiction.

name: Build Linux

on:

  workflow_dispatch: {}

  release:
    types: [created]

  # repository_dispatch:
  #   types: [eccodes-updated, magics-updated]

  push:
    branches:
    - master
    paths:
    - 'scripts/common.sh'
    - 'scripts/build-linux.sh'
    - 'scripts/wheel-linux.sh'
    - 'tools/copy-licences.py'
  pull_request:
    branches:
    - master
    paths:
    - 'scripts/common.sh'
    - 'scripts/build-linux.sh'
    - 'scripts/wheel-linux.sh'
    - 'tools/copy-licences.py'


jobs:
  build_legacy:

    runs-on: ubuntu-latest
    container: dockcross/manylinux2014-x64:20211222-f096312

    name: Legacy build manylinux2014

    steps:
    - uses: actions/checkout@v2

    - run: ./scripts/build-linux.sh


    ################################################################
    - run: ./scripts/wheel-linux.sh 3.6
    - uses: actions/upload-artifact@v2
      name: Upload wheel 3.6
      with:
        name: wheel-manylinux2014-3.6
        path: wheelhouse/*.whl

  build:

    runs-on: ubuntu-latest
    container: dockcross/manylinux2014-x64:latest

    name: Build manylinux2014

    steps:
    - uses: actions/checkout@v2

    - run: ./scripts/build-linux.sh

    ################################################################
    - run: ./scripts/wheel-linux.sh 3.7
    - uses: actions/upload-artifact@v2
      name: Upload wheel 3.7
      with:
        name: wheel-manylinux2014-3.7
        path: wheelhouse/*.whl

    ################################################################
    - run: ./scripts/wheel-linux.sh 3.8
    - uses: actions/upload-artifact@v2
      name: Upload wheel 3.8
      with:
        name: wheel-manylinux2014-3.8
        path: wheelhouse/*.whl

    ################################################################
    - run: ./scripts/wheel-linux.sh 3.9
    - uses: actions/upload-artifact@v2
      name: Upload wheel 3.9
      with:
        name: wheel-manylinux2014-3.9
        path: wheelhouse/*.whl

    ################################################################
    - run: ./scripts/wheel-linux.sh 3.10
    - uses: actions/upload-artifact@v2
      name: Upload wheel 3.10
      with:
        name: wheel-manylinux2014-3.10

        path: wheelhouse/*.whl
    ################################################################
    - run: ./scripts/wheel-linux.sh 3.11
    - uses: actions/upload-artifact@v2
      name: Upload wheel 3.11
      with:
        name: wheel-manylinux2014-3.11
        path: wheelhouse/*.whl

  test:

    needs: build

    strategy:
      fail-fast: false
      matrix: # We don't test 3.6, as it is not supported anymore by github actions
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    runs-on: ubuntu-latest

    name: Test with ${{ matrix.python-version }}

    steps:

    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - uses: actions/download-artifact@v2
      with:
        name: wheel-manylinux2014-${{ matrix.python-version }}

    - run: pip install *.whl

    - run: pip install -r tests/requirements.txt

    - run: pip freeze

    - run: env | sort

    - name: Get some data
      run: |
        curl -L https://get.ecmwf.int/repository/test-data/metview/gallery/2m_temperature.grib -o data.grib
        curl -L https://github.com/ecmwf/climetlab/raw/main/docs/examples/test.grib -o climetlab.grib
        curl -L https://github.com/ecmwf/climetlab/raw/main/docs/examples/test.nc -o climetlab.nc
        ls -l
      working-directory: tests

    - run: pytest -v -s
      working-directory: tests

    - uses: actions/upload-artifact@v2
      with:
        name: tests-manylinux2014-${{ matrix.python-version }}
        path: tests/*.png

  deploy:

    if: ${{ github.event_name == 'release' }}

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10", "3.11"]

    needs: [test, build, build_legacy]

    name: Deploy wheel ${{ matrix.python-version }}

    runs-on: ubuntu-latest


    steps:

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        # We cannot use 3.6 as it is not supported anymore by github actions
        # but we still want to deploy the wheels we built for it
        python-version: "3.10"

    - run: pip install twine

    - uses: actions/download-artifact@v2
      with:
        name: wheel-manylinux2014-${{ matrix.python-version }}

    - run: twine upload *.whl
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
