# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Test Universal

on:
  workflow_dispatch: {}

jobs:
  checks:
    name: Checks

    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install packages
        run: |
          pip install black pytest flake8 isort

      - name: Code QA
        run: |
          black --version
          isort --check --profile=black .
          black --check .
          flake8 .

      - run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel
          python setup.py bdist_wheel --universal
          pip install dist/ecmwflibs*none-any.whl
          mv ecmwflibs ecmwflibs.no
          rm -fr dist *.egg*
          ls -l

      - shell: python
        run: |
          import ecmwflibs
          print(ecmwflibs.__file__)
          assert ecmwflibs.universal()
